#!/bin/bash
export PATH="$SNAP/usr/share/maven/bin:$PATH"
export PATH="$SNAP/usr/lib/jvm/java-21-openjdk-amd64/bin:$PATH"
echo "final PATH: $PATH" >&2
echo "check 'which mvn': $(which mvn)" >&2
echo "check 'which jdeps': $(which jdeps)" >&2
exec $SNAP/bin/java -jar $SNAP/jar/jmodules.jar "$@"